/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class klt2000_kma_KLT2000JNI */

#ifndef _Included_klt2000_kma_KLT2000JNI
#define _Included_klt2000_kma_KLT2000JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     klt2000_kma_KLT2000JNI
 * Method:    getstems
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_klt2000_kma_KLT2000JNI_getstems
  (JNIEnv *, jobject, jstring);

/*
 * Class:     klt2000_kma_KLT2000JNI
 * Method:    getstems2
 * Signature: (Ljava/lang/String;[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_klt2000_kma_KLT2000JNI_getstems2
  (JNIEnv *, jobject, jstring, jobjectArray);

/*
 * Class:     klt2000_kma_KLT2000JNI
 * Method:    open_HAM_index
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_klt2000_kma_KLT2000JNI_open_1HAM_1index
  (JNIEnv *, jobject);

/*
 * Class:     klt2000_kma_KLT2000JNI
 * Method:    close_HAM_index
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_klt2000_kma_KLT2000JNI_close_1HAM_1index
  (JNIEnv *, jobject);

/*
 * Class:     klt2000_kma_KLT2000JNI
 * Method:    get_stems
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_klt2000_kma_KLT2000JNI_get_1stems
  (JNIEnv *, jobject, jstring);

/*
 * Class:     klt2000_kma_KLT2000JNI
 * Method:    get_stems2
 * Signature: (Ljava/lang/String;[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_klt2000_kma_KLT2000JNI_get_1stems2
  (JNIEnv *, jobject, jstring, jobjectArray);

/*
 * Class:     klt2000_kma_KLT2000JNI
 * Method:    get_terms_file
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_klt2000_kma_KLT2000JNI_get_1terms_1file
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
